let elencoFlamengo = [
    {
        imagem:"imagens/rossi.png",
        nome: "Agustín Rossi",
        nomeCompleto: "Agustín Sebastián Rossi",
        posicao: "Goleiro",
        numeroCamisa: 1,
        dataNascimento: "21/08/1995",
        nacionalidade: "Argentina",
        altura: 1.93,
        peso: 85,
        pePreferencial: "Esquerdo",
        clubesAnteriores: ["Boca Juniors"],
        titulos: ["Campeonato Argentino"],
    },
    {
        nome: "Matheus Cunha",
        nomeCompleto: "Matheus Gonçalves Cunha",
        posicao: "Goleiro",
        numeroCamisa: 25,
        dataNascimento: "24/05/2001",
        nacionalidade: "Brasileira",
        altura: 1.93,
        peso: 80,
        pePreferencial: "Direito",
        clubesAnteriores: ["CR Flamengo B"],
        titulos: ["Copa do Brasil"],
    },
    {
        nome: "David Luiz",
        nomeCompleto: "David Luiz Moreira Marinho",
        posicao: "Zagueiro",
        numeroCamisa: 23,
        dataNascimento: "22/04/1987",
        nacionalidade: "Brasileira",
        altura: 1.89,
        peso: 85,
        pePreferencial: "Direito",
        clubesAnteriores: ["Vitória", "Benfica", "Chelsea", "Paris Saint-Germain", "Arsenal"],
        titulos: ["Premier League", "Champions League", "Copa da França", "Campeonato Brasileiro", "Copa Libertadores"],
    },
    {
        nome: "Léo Ortiz",
        nomeCompleto: "Leonardo da Silva Ortiz",
        posicao: "Zagueiro",
        numeroCamisa: 3,
        dataNascimento: "18/11/1994",
        nacionalidade: "Brasileira",
        altura: 1.87,
        peso: 80,
        pePreferencial: "Direito",
        clubesAnteriores: ["Red Bull Bragantino"],
        titulos: ["Campeonato Brasileiro Série B"],
    },
    {
        nome: "Léo Pereira",
        nomeCompleto: "Leonardo Pereira",
        posicao: "Zagueiro",
        numeroCamisa: 4,
        dataNascimento: "31/01/1996",
        nacionalidade: "Brasileira",
        altura: 1.89,
        peso: 83,
        pePreferencial: "Esquerdo",
        clubesAnteriores: ["Guaratinguetá", "Náutico", "Orlando City", "Orlando City B","Athletico PR"],
        titulos: ["Campeonato Carioca"], // Adicione outros títulos conforme necessário
    },
    {
        nome: "Fabrício Bruno",
        nomeCompleto: "Fabrício Bruno Pires",
        posicao: "Zagueiro",
        numeroCamisa: 15,
        dataNascimento: "16/09/1996",
        nacionalidade: "Brasileira",
        altura: 1.86,
        peso: 80,
        pePreferencial: "Direito",
        clubesAnteriores: ["Real Betis B", "Deportivo Alavés B", "Real Madrid Castilla"],
        titulos: ["Campeonato Brasileiro"], // Adicione outros títulos conforme necessário
    },
    {
        nome: "Cleiton",
        nomeCompleto: "Cleiton Santana dos Santos",
        posicao: "Zagueiro",
        numeroCamisa: 33,
        dataNascimento: "25/04/2003",
        nacionalidade: "Brasileira",
        altura: 1.94,
        peso: 61,
        pePreferencial: "Canhoto",
        clubesAnteriores: ["Canaã"], // Adicione outros clubes se houver
        titulos: ["Brasileiro Sub-20"],
    },
    {
        nome: "Ayrton Lucas",
        nomeCompleto: "Ayrton Lucas da Silva",
        posicao: "Lateral-esquerdo",
        numeroCamisa: 6,
        dataNascimento: "08/09/1998",
        nacionalidade: "Brasileira",
        altura: 1.75,
        peso: 68,
        pePreferencial: "Esquerdo",
        clubesAnteriores: ["Spartak Moscou", "Fluminense"],
        titulos: ["Campeonato Brasileiro"],
    },
    {
        nome: "Alex Sandro",
        nomeCompleto: "Alex Sandro Lobo Silva",
        posicao: "Lateral-esquerdo",
        numeroCamisa: 26,
        dataNascimento: "26/01/1991",
        nacionalidade: "Brasileira",
        altura: 1.80,
        peso: 76,
        pePreferencial: "Esquerdo",
        clubesAnteriores: ["Atlético-MG", "Porto", "Juventus"],
        titulos: ["Campeonato Brasileiro", "Serie A Italiana", "Copa da Itália", "Supercopa da Itália"],
    },
    {
        nome: "Wesley",
        nomeCompleto: "Wesley de Souza Gomes",
        posicao: "Lateral-direito",
        numeroCamisa: 43,
        dataNascimento: "16/04/2004",
        nacionalidade: "Brasileira",
        altura: 1.78,
        peso: 70,
        pePreferencial: "Direito",
        clubesAnteriores: ["Flamengo Sub-20"],
        titulos: ["Campeonato Brasileiro Sub-20"],
    },
    {
        nome: "Matías Viña",
        nomeCompleto: "Matías Nicolás Viña Susperreguy",
        posicao: "Lateral-Esquerdo",
        numeroCamisa: 17,
        dataNascimento: "09/11/1997",
        nacionalidade: "Uruguaia",
        altura: 1.80,
        peso: 75,
        pePreferencial: "Esquerdo",
        clubesAnteriores: ["Palmeiras", "Roma", "Bournemouth"],
        titulos: ["Campeonato Brasileiro", "Copa Libertadores", "Copa do Brasil", "Europa Conference League"],
    },
    {
        nome: "Guillermo Varela",
        nomeCompleto: "Guillermo Varela Casal",
        posicao: "Lateral-direito",
        numeroCamisa: 2,
        dataNascimento: "24/03/1993",
        nacionalidade: "Uruguaia",
        altura: 1.80,
        peso: 75,
        pePreferencial: "Direito",
        clubesAnteriores: ["Peñarol", "Manchester United", "Real Madrid", "Eintracht Frankfurt"],
        titulos: ["Campeonato Uruguaio", "Copa do Brasil"],
    },
    {
        nome: "Allan",
        nomeCompleto: "Allan Rodrigues de Souza",
        posicao: "Volante",
        numeroCamisa: 21,
        dataNascimento: "03/03/1997",
        nacionalidade: "Brasileira",
        altura: 1.72,
        peso: 70,
        pePreferencial: "Direito",
        clubesAnteriores: ["Internacional", "Liverpool", "Watford", "Napoli", "Atlético-MG"],
        titulos: ["Campeonato Brasileiro", "Copa do Brasil", "Campeonato Mineiro"],
    },
    {
        nome: "Erick Pulgar",
        nomeCompleto: "Erick Andrés Pulgar Vargas",
        posicao: "Volante",
        numeroCamisa: 5,
        dataNascimento: "15/01/1994",
        nacionalidade: "Chilena",
        altura: 1.80,
        peso: 75,
        pePreferencial: "Direito",
        clubesAnteriores: ["Universidad Católica", "Bologna", "Fiorentina"],
        titulos: ["Campeonato Chileno", "Copa Sul-Americana"],
    },
    {
        nome: "Nicolas de La Cruz",
        nomeCompleto: "Nicolas de La Cruz",
        posicao: "Meia",
        numeroCamisa: 18,
        dataNascimento: "30/06/1997",
        nacionalidade: "Uruguaia",
        altura: 1.78,
        peso: 72,
        pePreferencial: "Direito",
        clubesAnteriores: ["Liverpool de Montevideo"],
        titulos: ["Campeonato Uruguaio"],
    },
    {
        nome: "Carlos Alcaraz",
        nomeCompleto: "Carlos Alcaraz Garfia",
        posicao: "Meia",
        numeroCamisa: 37,
        dataNascimento: "5/2/2001",
        nacionalidade: "Argentino",
        altura: 1.83,
        peso: 72,
        pePreferencial: "Direito",
        clubesAnteriores: ["Recing", "Southampton"],
        titulos: [],
    },
    {
        nome: "Gerson",
        nomeCompleto: "Gerson Santos da Silva",
        posicao: "Volante",
        numeroCamisa: 8,
        dataNascimento: "20/05/1997",
        nacionalidade: "Brasileira",
        altura: 1.75,
        peso: 70,
        pePreferencial: "Direito",
        clubesAnteriores: ["Fluminense", "Roma", "Fiorentina"],
        titulos: ["Campeonato Brasileiro", "Copa do Brasil"],
    },
    {
        nome: "Giorgian de Arrascaeta",
        nomeCompleto: "Giorgian De Arrascaeta",
        posicao: "Meia",
        numeroCamisa: 14,
        dataNascimento: "1/6/1994",
        nacionalidade: "Uruguaia",
        altura: 1.75,
        peso: 68,
        pePreferencial: "Esquerdo",
        clubesAnteriores: ["Defensor Sporting", "Cruzeiro"],
        titulos: ["Campeonato Brasileiro", "Copa do Brasil"],
    },
    {
        nome: "Lorran",
        nomeCompleto: "Lorran de Souza",
        posicao: "Lateral-esquerdo",
        numeroCamisa: 319,
        dataNascimento: "14/03/2003",
        nacionalidade: "Brasileira",
        altura: 1.78,
        peso: 70,
        pePreferencial: "Esquerdo",
        clubesAnteriores: ["Flamengo Sub-20"],
        titulos: ["Campeonato Brasileiro Sub-20"],
    },
    {
        nome: "Everton Cebolinha",
        nomeCompleto: "Everton Sousa Soares",
        posicao: "Atacante",
        numeroCamisa: 11,
        dataNascimento: "22/03/1996",
        nacionalidade: "Brasileira",
        altura: 1.65,
        peso: 65,
        pePreferencial: "Esquerdo",
        clubesAnteriores: ["Grêmio", "Benfica"],
        titulos: ["Campeonato Brasileiro", "Copa Libertadores"],
    },
    {
        nome: "Michael",
        nomeCompleto: "Michael Oliveira",
        posicao: "Atacante",
        numeroCamisa: 30,
        dataNascimento: "31/03/1994",
        nacionalidade: "Brasileira",
        altura: 1.70,
        peso: 68,
        pePreferencial: "Direito",
        clubesAnteriores: ["Goiás", "Flamengo", "Al-Hilal"],
        titulos: ["Campeonato Brasileiro", "Copa Libertadores"],
    },
    {
        nome: "Bruno Henrique",
        nomeCompleto: "Bruno Henrique Pinto",
        posicao: "Atacante",
        numeroCamisa: 27,
        dataNascimento: "04/04/1990",
        nacionalidade: "Brasileira",
        altura: 1.78,
        peso: 75,
        pePreferencial: "Esquerdo",
        clubesAnteriores: ["Santos", "Wolfsburg", "Athletico-MG"],
        titulos: ["Campeonato Brasileiro", "Copa Libertadores", "Recopa Sul-Americana", "Copa do Brasil"],
    },
    {
        nome: "Gabigol",
        nomeCompleto: "Gabriel Barbosa Almeida",
        posicao: "Atacante",
        numeroCamisa: 99,
        dataNascimento: "30/08/1996",
        nacionalidade: "Brasileira",
        altura: 1.77,
        peso: 75,
        pePreferencial: "Direito",
        clubesAnteriores: ["Santos", "Inter de Milão", "Benfica"],
        titulos: ["Campeonato Brasileiro", "Copa Libertadores", "Recopa Sul-Americana", "Copa do Brasil"],
    },
    {
        nome: "Matheus Gonçalves",
        nomeCompleto: "Matheus Gonçalves",
        posicao: "Meia",
        numeroCamisa: 20, // Adapte conforme o número atual
        dataNascimento: "15/02/2004",
        nacionalidade: "Brasileira",
        altura: 1.75,
        peso: 68,
        pePreferencial: "Direito",
        clubesAnteriores: ["Flamengo Sub-20"],
        titulos: ["Campeonato Brasileiro Sub-20"],
    },
    {
        nome: "Pedro",
        nomeCompleto: "Pedro Guilherme Abreu dos Santos",
        posicao: "Atacante",
        numeroCamisa: 9, // Adapte conforme o número atual
        dataNascimento: "20 /07/1997",
        nacionalidade: "Brasileira",
        altura: 1.86,
        peso: 80,
        pePreferencial: "Direito",
        clubesAnteriores: ["Fluminense", "Fiorentina"],
        titulos: ["Campeonato Brasileiro", "Copa Libertadores", "Copa do Brasil"],
    },
    {
        nome: "Gonzalo Plata",
        nomeCompleto: "Gonzalo Plata",
        posicao: "Atacante",
        numeroCamisa: 45,
        dataNascimento: "01/11/1999",
        nacionalidade: "Equatoriana",
        altura: 1.70,
        peso: 68,
        pePreferencial: "Direito",
        clubesAnteriores: ["Real Valladolid", "Sporting CP", "Al Sadd"],
        titulos: [],

    },
    {
        nome: "Carlinhos",
        nomeCompleto: "Carlos Moisés de Lima",
        posicao: "Atacante",
        numeroCamisa: 22,
        dataNascimento: "12/02/1997",
        nacionalidade: "Brasileira",
        altura: 1.95,
        peso: 82,
        pePreferencial: "Destro",
        clubesAnteriores: ["Nova Iguaçu", "Audax-RJ", "Corinthians", "São Caetano", "Novorizontino", "Vila Nova"],
        titulos: [], // Adicionar títulos conforme conquistados
    },

];